export const navGroups = [
  {
    id: 'basics',
    title: 'Основы',
    items: [
      { id: 'block', label: 'TaoBlock' },
      { id: 'button', label: 'TaoButton', aliases: ['text', 'tone'] },
      { id: 'card', label: 'TaoCard' },
      { id: 'copy', label: 'TaoCopy' },
    ],
  },
  {
    id: 'forms',
    title: 'Формы',
    items: [
      { id: 'input', label: 'TaoInput / Group', aliases: ['TaoInput', 'TaoInputGroup'] },
      { id: 'input-number', label: 'TaoInputNumber' },
      { id: 'quantity', label: 'TaoQuantity' },
      { id: 'textarea', label: 'TaoTextarea' },
      { id: 'checkbox', label: 'TaoCheckbox' },
      { id: 'select', label: 'Select / Switch / Radio', aliases: ['TaoSelect', 'TaoSwitch', 'TaoRadio', 'TaoFormField', 'FormField'] },
      { id: 'segmented', label: 'TaoSegmented', aliases: ['TaoSegmentedOption', 'Segmented'] },
      { id: 'combobox', label: 'TaoCombobox' },
      { id: 'typeahead', label: 'Typeahead (demo)', aliases: ['autocomplete', 'remote', 'поиск'] },
      { id: 'date', label: 'TaoDate / Range', aliases: ['TaoDate', 'TaoDateRange', 'DateRange'] },
      { id: 'pincode', label: 'TaoPinCode' },
      { id: 'slider', label: 'Progress / Slider', aliases: ['TaoProgress', 'TaoSlider'] },
      { id: 'filedrop', label: 'TaoFileDrop' },
    ],
  },
  {
    id: 'data',
    title: 'Данные',
    items: [
      { id: 'table', label: 'TaoTable' },
      { id: 'pagination', label: 'TaoPagination' },
      { id: 'empty', label: 'TaoEmpty' },
      { id: 'list', label: 'TaoList', aliases: ['TaoListItem', 'ListItem', 'список'] },
      { id: 'stages', label: 'TaoStages' },
      { id: 'skeleton', label: 'TaoSkeleton' },
      { id: 'counter', label: 'TaoCounter' },
      { id: 'carousel', label: 'TaoCarousel' },
    ],
  },
  {
    id: 'layout',
    title: 'Макет',
    items: [
      { id: 'container', label: 'TaoContainer' },
      { id: 'flex', label: 'Flex / Space', aliases: ['TaoFlex', 'TaoSpace'] },
      { id: 'grid', label: 'Grid (demo)', aliases: ['masonry', 'плитки', 'каталог', 'сетка', 'GridPlayground'] },
      { id: 'divider', label: 'TaoDivider' },
      { id: 'split', label: 'TaoSplit' },
      { id: 'fieldset', label: 'TaoFieldset' },
      { id: 'animated-border', label: 'TaoAnimatedBorder' },
    ],
  },
  {
    id: 'overlays',
    title: 'Оверлеи',
    items: [
      { id: 'modal', label: 'TaoModal' },
      { id: 'drawer', label: 'TaoDrawer' },
      { id: 'confirm', label: 'confirm()' },
      { id: 'tooltip', label: 'TaoTooltip' },
      { id: 'popover', label: 'TaoPopover' },
      { id: 'dropdown', label: 'TaoDropdownMenu' },
      { id: 'spoiler', label: 'Spoiler / Group', aliases: ['TaoSpoiler', 'TaoSpoilerGroup'] },
    ],
  },
  {
    id: 'nav',
    title: 'Навигация',
    items: [
      { id: 'tabs', label: 'TaoTabs' },
      { id: 'breadcrumb', label: 'TaoBreadcrumb' },
      { id: 'link', label: 'TaoLink' },
      { id: 'scrolltop', label: 'TaoScrollTop' },
    ],
  },
  {
    id: 'feedback',
    title: 'Обратная связь',
    items: [
      { id: 'toast', label: 'toast()' },
      { id: 'alert', label: 'TaoAlert' },
      { id: 'tag', label: 'TaoTag', aliases: ['closable', 'chip', 'flat'] },
      { id: 'loader', label: 'TaoLoader' },
    ],
  },
  {
    id: 'media',
    title: 'Медиа',
    items: [
      { id: 'image', label: 'TaoImage' },
      { id: 'avatar', label: 'TaoAvatar' },
      { id: 'icon', label: 'TaoIcon' },
    ],
  },
]
